FROM golang:1.25-alpine

WORKDIR /app

# Install git and air for hot reloading
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Run the application using go run
CMD ["go", "run", "main.go"]
